a= input('Digite algo para ser disecado: ')
print("O tipo primitivo desse valor é", type(a))
print('Só têm espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alphanúmerico?', a.isalnum())
print('Está em Maiusculo?', a.isupper())
print('Está em mínusculo?', a.islower())
print('Está captabilizada?', a.istitle())